name: local_auth
description: Flutter plugin for Android and iOS device authentication sensors
  such as Fingerprint Reader and Touch ID.
homepage: https://github.com/flutter/plugins/tree/master/packages/local_auth
version: 0.4.0+1

flutter:
  plugin:
    androidPackage: io.flutter.plugins.localauth
    iosPrefix: FLT
    pluginClass: LocalAuthPlugin

dependencies:
  flutter:
    sdk: flutter
  meta:
  intl: ^0.17.0

environment:
  sdk: ">=2.12.0 <3.0.0"

